name = "VoronoiMeshDataStruct"
uuid = "8a938a65-3ddb-45e8-9de7-ea9d95686e1a"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ImmutableVectors = "d6059b30-97e8-4ff2-b426-20b29c0469af"
TensorsLite = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"
TensorsLiteGeometry = "f9cc0174-84f8-4243-a119-6cf6c33db921"
Zeros = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
GeometryBasicsExt = "GeometryBasics"
NCDatasetsExt = "NCDatasets"

[compat]
julia = "1.9"
GeometryBasics = "0.4"

[extras]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "NCDatasets", "LinearAlgebra"]
